[package]
name = "hayro-interpret"
version = "0.1.0"
edition = "2024"

[dependencies]
hayro-syntax = { workspace = true }
kurbo = { workspace = true }
peniko = { workspace = true }
smallvec = { workspace = true }
log = { workspace = true }
qcms=  { workspace = true }
phf = { workspace = true, features = ["macros"] }
skrifa = { workspace = true }
yoke = { workspace = true, features = ["derive"]}
hayro-font = { workspace = true }
bitflags = { workspace = true }

[features]
default = []
jpeg2000 = ["hayro-syntax/jpeg2000"]
