[package]
name = "hayro-interpret"
version = "0.1.0"
edition = "2024"

[dependencies]
hayro-syntax = { workspace = true }
kurbo = { workspace = true }
peniko = { workspace = true }
smallvec = { workspace = true }