[package]
name = "hayro-interpret"
version = "0.1.0"
edition = "2024"

[dependencies]
hayro-syntax = { workspace = true }
kurbo = { workspace = true }
peniko = { workspace = true }
smallvec = { workspace = true }
log = { workspace = true }
qcms=  { workspace = true }
walkdir = { workspace = true }
once_cell = "1.21.3"
phf = { workspace = true, features = ["macros"] }
skrifa = { version = "0.30.0" }
yoke = { workspace = true, features = ["derive"]}
fontdb = "0.23.0"
bitflags = "2.9.0"
