[package]
name = "hayro-interpret"
version = "0.1.0"
edition = "2024"

[dependencies]
hayro-syntax = { path = "../hayro-syntax", default-features = false }
kurbo = { workspace = true }
peniko = { workspace = true }
smallvec = { workspace = true }
log = { workspace = true }
qcms=  { workspace = true }
once_cell = "1.21.3"
phf = { workspace = true, features = ["macros"] }
skrifa = { workspace = true }
yoke = { workspace = true, features = ["derive"]}
hayro-fonts = { workspace = true }
bitflags = "2.9.0"

[features]
default = ["jpeg2000"]
jpeg2000 = ["hayro-syntax/jpeg2000"]
