[package]
name = "hayro-syntax"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = { workspace = true }
log = { workspace = true }
kurbo = { workspace = true }
rustc-hash = { workspace = true }
smallvec = { workspace = true }
zune-jpeg = { workspace = true }
miniz_oxide = { workspace = true }
itertools = { workspace = true }
jpeg2k = { version = "0.9.1", default-features = false, features = ["openjp2"], optional = true }

[features]
default = ["jpeg2000"]
jpeg2000 = ["dep:jpeg2k"]

[dev-dependencies]
walkdir = "2.5.0"
