[package]
name = "hayro-syntax"
version = "0.0.1"
description = "A low-level crate for reading PDF files."
edition = { workspace = true }
license = { workspace = true }

[dependencies]
hex = { workspace = true }
log = { workspace = true }
kurbo = { workspace = true }
rustc-hash = { workspace = true }
smallvec = { workspace = true }
zune-jpeg = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
jpeg2k = { workspace = true, optional = true }
flate2 = { workspace = true }

[features]
default = []
jpeg2000 = ["dep:jpeg2k"]
