[package]
name = "hayro-tests"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
publish = false
autotests = false

[[test]]
name = "tests"
path = "tests/mod.rs"

[dependencies]
hayro-render = { path = "../hayro-render", features = ["jpeg2000"] }

[dev-dependencies]
once_cell = { workspace = true }
image = {  workspace = true }
oxipng = { workspace = true }
