[package]
name = "hayro-tests"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
publish = false
autotests = false

[[test]]
name = "tests"
path = "tests/mod.rs"

[dependencies]
hayro-render = { path = "../hayro-render", features = ["jpeg2000"] }

[dev-dependencies]
once_cell = { workspace = true }
walkdir = "2.5.0"
log = "0.4.27"
image = "0.25.6"
oxipng = "9.1.5"
