[package]
name = "hayro-render"
version = "0.1.0"
edition = "2024"
autotests = false


[dependencies]
hayro-syntax = { workspace = true }
hayro-interpret = { workspace = true }
image = "0.25.6"
vello_cpu = { workspace = true }
vello_common = { workspace = true }
vello_api = { workspace = true }

[[test]]
name = "tests"
path = "tests/mod.rs"


[dev-dependencies]
walkdir = "2.5.0"
log = "0.4.27"
image = "0.25.6"

