name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  checks:
    name: Check clippy, formatting, and documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88.0
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-hack
      - run: RUSTFLAGS="-D warnings" cargo clippy -p hayro-syntax
      - run: cargo fmt --check --all
      - run: RUSTFLAGS="-D warnings" cargo doc -p hayro-syntax --no-deps
      - run: RUSTFLAGS="-D warnings" cargo hack check --each-feature -p hayro-syntax