name: Deploy to GitHub Pages

on:
  # Manual trigger only
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        
      - name: Build WASM module
        run: |
          cd hayro-demo
          wasm-pack build --target web --out-dir www
          
      - name: Prepare deployment
        run: |
          cd hayro-demo
          # Create deployment directory
          mkdir -p dist
          
          # Copy all static files
          cp www/index.html dist/
          cp www/styles.css dist/
          cp www/index.js dist/
          
          # Copy generated WASM files
          cp www/hayro_demo_bg.wasm dist/
          cp www/hayro_demo.js dist/
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'hayro-demo/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4